# Generated by Django 4.2 on 2023-05-14 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.IntegerField()),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('precio', models.IntegerField(blank=True, default=0, null=True)),
                ('carrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.carrito')),
            ],
        ),
    ]
