# Generated by Django 4.2 on 2023-05-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='id_producto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='producto',
            field=models.CharField(max_length=200),
        ),
    ]
